// Generated by gencpp from file topic_pkg/Topic.msg
// DO NOT EDIT!


#ifndef TOPIC_PKG_MESSAGE_TOPIC_H
#define TOPIC_PKG_MESSAGE_TOPIC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace topic_pkg
{
template <class ContainerAllocator>
struct Topic_
{
  typedef Topic_<ContainerAllocator> Type;

  Topic_()
    : usia(0)
    , tinggi(0.0)
    , nama()
    , kehadiran(false)  {
    }
  Topic_(const ContainerAllocator& _alloc)
    : usia(0)
    , tinggi(0.0)
    , nama(_alloc)
    , kehadiran(false)  {
  (void)_alloc;
    }



   typedef int64_t _usia_type;
  _usia_type usia;

   typedef double _tinggi_type;
  _tinggi_type tinggi;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _nama_type;
  _nama_type nama;

   typedef uint8_t _kehadiran_type;
  _kehadiran_type kehadiran;





  typedef boost::shared_ptr< ::topic_pkg::Topic_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::topic_pkg::Topic_<ContainerAllocator> const> ConstPtr;

}; // struct Topic_

typedef ::topic_pkg::Topic_<std::allocator<void> > Topic;

typedef boost::shared_ptr< ::topic_pkg::Topic > TopicPtr;
typedef boost::shared_ptr< ::topic_pkg::Topic const> TopicConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::topic_pkg::Topic_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::topic_pkg::Topic_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::topic_pkg::Topic_<ContainerAllocator1> & lhs, const ::topic_pkg::Topic_<ContainerAllocator2> & rhs)
{
  return lhs.usia == rhs.usia &&
    lhs.tinggi == rhs.tinggi &&
    lhs.nama == rhs.nama &&
    lhs.kehadiran == rhs.kehadiran;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::topic_pkg::Topic_<ContainerAllocator1> & lhs, const ::topic_pkg::Topic_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace topic_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::topic_pkg::Topic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::topic_pkg::Topic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topic_pkg::Topic_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topic_pkg::Topic_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topic_pkg::Topic_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topic_pkg::Topic_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::topic_pkg::Topic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ad8335939c8d987f5e0189e0ca2b800";
  }

  static const char* value(const ::topic_pkg::Topic_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ad8335939c8d987ULL;
  static const uint64_t static_value2 = 0xf5e0189e0ca2b800ULL;
};

template<class ContainerAllocator>
struct DataType< ::topic_pkg::Topic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "topic_pkg/Topic";
  }

  static const char* value(const ::topic_pkg::Topic_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::topic_pkg::Topic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 usia\n"
"float64 tinggi\n"
"string nama\n"
"bool kehadiran\n"
;
  }

  static const char* value(const ::topic_pkg::Topic_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::topic_pkg::Topic_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.usia);
      stream.next(m.tinggi);
      stream.next(m.nama);
      stream.next(m.kehadiran);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Topic_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::topic_pkg::Topic_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::topic_pkg::Topic_<ContainerAllocator>& v)
  {
    s << indent << "usia: ";
    Printer<int64_t>::stream(s, indent + "  ", v.usia);
    s << indent << "tinggi: ";
    Printer<double>::stream(s, indent + "  ", v.tinggi);
    s << indent << "nama: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.nama);
    s << indent << "kehadiran: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.kehadiran);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOPIC_PKG_MESSAGE_TOPIC_H
