// Generated by gencpp from file service_pkg/VectorMagnitude.msg
// DO NOT EDIT!


#ifndef SERVICE_PKG_MESSAGE_VECTORMAGNITUDE_H
#define SERVICE_PKG_MESSAGE_VECTORMAGNITUDE_H

#include <ros/service_traits.h>


#include <service_pkg/VectorMagnitudeRequest.h>
#include <service_pkg/VectorMagnitudeResponse.h>


namespace service_pkg
{

struct VectorMagnitude
{

typedef VectorMagnitudeRequest Request;
typedef VectorMagnitudeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VectorMagnitude
} // namespace service_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_pkg::VectorMagnitude > {
  static const char* value()
  {
    return "55d1a215f43fd1f64eb105a505b172c4";
  }

  static const char* value(const ::service_pkg::VectorMagnitude&) { return value(); }
};

template<>
struct DataType< ::service_pkg::VectorMagnitude > {
  static const char* value()
  {
    return "service_pkg/VectorMagnitude";
  }

  static const char* value(const ::service_pkg::VectorMagnitude&) { return value(); }
};


// service_traits::MD5Sum< ::service_pkg::VectorMagnitudeRequest> should match
// service_traits::MD5Sum< ::service_pkg::VectorMagnitude >
template<>
struct MD5Sum< ::service_pkg::VectorMagnitudeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_pkg::VectorMagnitude >::value();
  }
  static const char* value(const ::service_pkg::VectorMagnitudeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_pkg::VectorMagnitudeRequest> should match
// service_traits::DataType< ::service_pkg::VectorMagnitude >
template<>
struct DataType< ::service_pkg::VectorMagnitudeRequest>
{
  static const char* value()
  {
    return DataType< ::service_pkg::VectorMagnitude >::value();
  }
  static const char* value(const ::service_pkg::VectorMagnitudeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_pkg::VectorMagnitudeResponse> should match
// service_traits::MD5Sum< ::service_pkg::VectorMagnitude >
template<>
struct MD5Sum< ::service_pkg::VectorMagnitudeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_pkg::VectorMagnitude >::value();
  }
  static const char* value(const ::service_pkg::VectorMagnitudeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_pkg::VectorMagnitudeResponse> should match
// service_traits::DataType< ::service_pkg::VectorMagnitude >
template<>
struct DataType< ::service_pkg::VectorMagnitudeResponse>
{
  static const char* value()
  {
    return DataType< ::service_pkg::VectorMagnitude >::value();
  }
  static const char* value(const ::service_pkg::VectorMagnitudeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_PKG_MESSAGE_VECTORMAGNITUDE_H
